version: "3.3"
services:
  axies-next:
    container_name: axies-next
    restart: always
    image: node:20.10.0
    ports:
      - 5000:4006
    environment:
      - PORT=4006
    volumes:
      - ./:/usr/src/axies-next
    working_dir: /usr/src/axies-next

    networks:
      - client-network

    # FOR PRODUCTION
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge


# axies-next: localhost:5000 <==> container: 4006
# axies-api: localhost:5001 <==> container: 4007
# axies-batch: localhost:5002 <==> container: 4008